# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviestuff', '0002_auto_20160323_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='generes',
            new_name='genres',
        ),
    ]
